"""
ForexMind — SQLAlchemy ORM Models
=====================================
Database schema for persisting candles, news, signals, and trades.

Advanced Python concepts:
  - SQLAlchemy 2.0 declarative ORM with type annotations
  - Mapped[] type hints (clean modern ORM style)
  - Enum types for constrained string fields
  - __repr__ using dataclass-style formatted output
"""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """All ORM models inherit from this base."""
    pass


# ── Enums ─────────────────────────────────────────────────────────────────────

class Direction(str, enum.Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class TradeStatus(str, enum.Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class SignalSource(str, enum.Enum):
    RULE_BASED = "rule_based"
    LIGHTGBM = "lightgbm"
    LSTM = "lstm"
    RL_AGENT = "rl_agent"
    ENSEMBLE = "ensemble"
    CLAUDE = "claude"


# ── Tables ─────────────────────────────────────────────────────────────────────

class Candle(Base):
    """
    OHLCV price candle.
    Primary key is (instrument, timeframe, time) for easy deduplication.
    """
    __tablename__ = "candles"
    __table_args__ = (
        UniqueConstraint("instrument", "timeframe", "time", name="uq_candle"),
        Index("ix_candle_lookup", "instrument", "timeframe", "time"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    instrument: Mapped[str] = mapped_column(String(16), nullable=False)
    timeframe: Mapped[str] = mapped_column(String(8), nullable=False)
    time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    open: Mapped[float] = mapped_column(Float, nullable=False)
    high: Mapped[float] = mapped_column(Float, nullable=False)
    low: Mapped[float] = mapped_column(Float, nullable=False)
    close: Mapped[float] = mapped_column(Float, nullable=False)
    volume: Mapped[float] = mapped_column(Float, default=0.0)

    def __repr__(self) -> str:
        return (
            f"Candle({self.instrument} {self.timeframe} "
            f"{self.time:%Y-%m-%d %H:%M} C={self.close:.5f})"
        )


class NewsArticle(Base):
    """Aggregated news article with sentiment score."""
    __tablename__ = "news_articles"
    __table_args__ = (
        Index("ix_news_time", "published_at"),
        Index("ix_news_instrument", "related_instrument"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    source: Mapped[str] = mapped_column(String(64), nullable=False)
    headline: Mapped[str] = mapped_column(String(512), nullable=False)
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    url: Mapped[Optional[str]] = mapped_column(String(1024), nullable=True)
    published_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    related_instrument: Mapped[Optional[str]] = mapped_column(String(16), nullable=True)
    sentiment_score: Mapped[float] = mapped_column(Float, default=0.0)  # -1.0 to +1.0
    impact: Mapped[str] = mapped_column(String(16), default="low")      # low/medium/high

    def __repr__(self) -> str:
        return f"News({self.source} | {self.headline[:60]}... | sentiment={self.sentiment_score:.2f})"


class EconomicEvent(Base):
    """Forex Factory / economic calendar event."""
    __tablename__ = "economic_events"
    __table_args__ = (
        Index("ix_event_time", "event_time"),
        Index("ix_event_currency", "currency"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    event_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    currency: Mapped[str] = mapped_column(String(8), nullable=False)
    title: Mapped[str] = mapped_column(String(256), nullable=False)
    impact: Mapped[str] = mapped_column(String(16), nullable=False)  # low/medium/high
    forecast: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    previous: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    actual: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    def __repr__(self) -> str:
        return f"Event({self.event_time:%Y-%m-%d %H:%M} {self.currency} {self.title} [{self.impact}])"


class Signal(Base):
    """Trading signal generated by any strategy."""
    __tablename__ = "signals"
    __table_args__ = (Index("ix_signal_time_instrument", "generated_at", "instrument"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    instrument: Mapped[str] = mapped_column(String(16), nullable=False)
    timeframe: Mapped[str] = mapped_column(String(8), nullable=False)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    direction: Mapped[str] = mapped_column(Enum(Direction), nullable=False)
    source: Mapped[str] = mapped_column(Enum(SignalSource), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)    # 0.0–1.0
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    stop_loss: Mapped[float] = mapped_column(Float, nullable=False)
    take_profit: Mapped[float] = mapped_column(Float, nullable=False)
    risk_pct: Mapped[float] = mapped_column(Float, default=1.0)
    reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Relationship: one signal can spawn one trade
    trade: Mapped[Optional["Trade"]] = relationship("Trade", back_populates="signal", uselist=False)

    def __repr__(self) -> str:
        return (
            f"Signal({self.instrument} {self.direction} @ {self.entry_price:.5f} "
            f"SL={self.stop_loss:.5f} TP={self.take_profit:.5f} "
            f"conf={self.confidence:.0%})"
        )


class Trade(Base):
    """Paper or live trade execution record."""
    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    signal_id: Mapped[Optional[int]] = mapped_column(ForeignKey("signals.id"), nullable=True)
    instrument: Mapped[str] = mapped_column(String(16), nullable=False)
    direction: Mapped[str] = mapped_column(Enum(Direction), nullable=False)
    units: Mapped[int] = mapped_column(Integer, nullable=False)
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    stop_loss: Mapped[float] = mapped_column(Float, nullable=False)
    take_profit: Mapped[float] = mapped_column(Float, nullable=False)
    exit_price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    opened_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    closed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    status: Mapped[str] = mapped_column(Enum(TradeStatus), default=TradeStatus.OPEN)
    pnl_pips: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    pnl_usd: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    oanda_trade_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    signal: Mapped[Optional[Signal]] = relationship("Signal", back_populates="trade")

    def __repr__(self) -> str:
        return (
            f"Trade({self.instrument} {self.direction} {self.units} units "
            f"@ {self.entry_price:.5f} [{self.status}] P&L={self.pnl_usd})"
        )
